name: production CI Pipeline

# Trigger workflow on push request to the production branch
on:
  push:
    branches:
      - "main"

jobs:
  call-reusable:
    name: Call Reusable Next.js CI Workflow
    # uses: ./.github/workflows/reuseablenext-workflow.yml
    uses: ./.github/workflows/test-workflow.yml
    with:
      node-version: '20.9.0'
      environment_name: 'production'
    secrets: inherit # This allows the reusable workflow to access secrets from the calling workflow's repository. Make sure to set the required secrets in the repository settings.